

game:main.o enigme1.o
	gcc main.o enigme1.o -o game  -lSDL -lSDL_image -lSDL_mixer -lSDL_ttf -g 

main.o:main.c
	gcc main.c -c  -lSDL -lSDL_image -lSDL_mixer -lSDL_ttf -g


enigme1.o:enigme1.c
	gcc enigme1.c -c -lSDL -lSDL_image -lSDL_mixer -lSDL_ttf -g
